
## This file contains files and directories that should
## be preserved during an upgrade.

# /etc/example.conf
# /etc/openvpn/

# 保留自定義腳本 (正確)
/etc/myscript/
/etc/init.d/pbr-cust
/etc/hotplug.d/iface/99-pbr-cust
/etc/hotplug.d/block/99-samba-auto-share

/etc/init.d/dbroute
/etc/dnsmasq.d/




# 保留 AdGuard Home 設定 (如果是存在 internal flash)
/srv/adguardhome/conf/

# 保留 QoSify 設定 (正確)
/etc/qosify/

# --- 刪除以下項目 ---
# /etc/init.d/              <-- 危險！會覆蓋系統腳本
# /overlay/upper/...        <-- 錯誤！請使用邏輯路徑 (/etc/...)
