# 域名路由 — 由 sync-googleconfig 自動生成，請勿手動修改
# === wg2 ===
nftset=/netflix.com/4#inet#fw4#route_wg2_v4
nftset=/nflxvideo.net/4#inet#fw4#route_wg2_v4
nftset=/nflximg.net/4#inet#fw4#route_wg2_v4
nftset=/nflxso.net/4#inet#fw4#route_wg2_v4
nftset=/nflxext.com/4#inet#fw4#route_wg2_v4
